### PR TITLE
Added highlighting for functions

### PR DESCRIPTION
**Pull request by ekalinin**
Without patch:
vimerl func without patch

With patch:
vimerl func with patch

Vim 7.4 & Ubuntu 13.10 with theme https://github.com/morhetz/gruvbox (dark)

### CODE REVIEW

**Comment by jimenezrick** [comment]
I like the idea but your regex highlights the left parentheses as well, which it isn't nice. Look at other similar regex that do this in the correct way.

**Comment by ekalinin** [comment]
> You should probably use a zero-width match to avoid matching the parenthesis. Check out :help /zero-width.

Bingo! Thanks @ehamberg !

Improved regexp: `"^\w\+\s*\((\)\@="`

**Comment by ehamberg** [comment]
That looks better, but I don't think you need to create a group, simply using `^\w\+\s*(\@=` should work. :)

**Comment by ekalinin** [comment]
> That looks better, but I don't think you need to create a group, ^\w+\s*(\@= should work. :)

Yep. You're right again. Thanks, man!

**Comment by jimenezrick** [comment]
Much better, but there is a corner case, Erlang function names are atoms, so a function like this is valid:
`'Foo Bar'(N) -> N+1.`

**Comment by ekalinin** [comment]
> Much better, but there is a corner case, Erlang function names are atoms, so a function like this is valid: 'Foo Bar'(N) -> N+1.

`/^'[^']\+'\s*(\@=/` ?

**Comment by ekalinin** [comment]
My current solution:

``` vim
syn match erlangFunc                        /^\w\+\s*(\@=/
syn match erlangFunc                        /^'[^']\+'\s*(\@=/
```

Result:
vimerl func with patch 2

**Comment by ekalinin** [comment]
Closing this pull request.
I'll create a new one with clear commit.

**Pull request closed without merging**
