### PR TITLE
Speed up compilation of erlang_indent.erl for R16B

### PR DESCRIPTION
**Pull request by evnu**
Should fix Bug #43

### CODE REVIEW

**Comment by jimenezrick** [comment]
Could you give a little bit of context how to this patch fixes the issue #43?

**Comment by evnu** [comment]
Apparently R16B gets "stuck" (taking a long time) by `parse_next2` due to the number of clauses. By splitting the function into two functions, R16B doesn't take as long to compile `indent/erlang_indent.erl`. I am not sure why the compiler is behaving that way and am currently unsure how to condense the file into a smaller one worthy a bug report against Erlang/OTP.

**Comment by jimenezrick** [comment]
Maybe the R16 compiler has troubles compiling function with so many clauses, strange...

**Comment by evnu** [comment]
I am pretty sure this is a compiler bug. When escript interprets the file without compiling it, is is fast enough. Compiling to native code is slow as well.

**Comment by jimenezrick** [comment]
So, commenting out `-mode(compile).` could be a quick fix until R16 is more mature. Running in interpreted mode is fast enough?

**Comment by evnu** [comment]
It seems to be fast enough on my machine.

**Comment by jimenezrick** [comment]
So, I prefer not to merge this pull request as there seems to be a compiler bug. And as a temporary fix, just comment out that line. Do you agree?

**Comment by evnu** [comment]
Sure, works for me. But how can this be communicated to R16B users?

**Comment by aerosol** [comment]
@evnu  http://erlang.org/mailman/listinfo/erlang-bugs

**Comment by evnu** [comment]
@aerosol I was more thinking how to communicate the temporary fix to users of vimerl. But I will file a bug for R16B later as well.

**Comment by jimenezrick** [comment]
Done: https://github.com/jimenezrick/vimerl/commit/c30483898334f7beaf00bd9be9a821efd16494df

**Comment by tex** [comment]
OK, thank you.

**Pull request closed without merging**
