### PR TITLE
Indentation borrowed from Vim 7.4

### PR DESCRIPTION
**Pull request by sumerman**
Indentation file which looks very compatible with emacs one, borrowed from Vim 7.4

### CODE REVIEW

**Comment by aerosol** [comment]
In case anyone would like to know, the up-to-date version is available here: https://github.com/vim-erlang/vim-erlang-runtime

**Comment by sumerman** [comment]
@aerosol thanks. 
@jimenezrick Since this indentation script apparently is evolving maybe it would be better to just add an indentation turn-off switch to vimerl instead of merging this.

**Comment by jimenezrick** [comment]
I see. So, if Vim 7.4 is shipping this script, I will add a check so that if Vim version is >= 7.4, my indenting script will be disabled. Also and option to override this behavior.

By the way, where is the repo with the shipped script? Because I see 2013-Jul-21 version in Vim official repo and 2013-Jun-01 in https://github.com/hcs42/vim-erlang-runtime.

**Comment by jimenezrick** [comment]
Please @sumerman, review the fix, reopen the issue if necessary.

**Comment by sumerman** [comment]
@jimenezrick it seems fine, thanks.

**Pull request closed without merging**
