### PR TITLE
Wrangler support rescued

### PR DESCRIPTION
**Pull request by quiquepaz**
- Variable Renaming
- Function Renaming
- Global Undo
- Function Extraction
- Unfortunately did not manage to put module renaming to work
- All the integrations work with wrangler 69def6ec21f9e0b696c2150710d09ca922aa8e8b (latest)
- Debugging traces still on
- Keep in mind you need to put erl_call in your path!!

### CODE REVIEW

**Comment by jimenezrick** [comment]
Is this the same version I removed? As I said I'm not especially
interesting in including it, as I am not going to maintain it...

On Fri, Oct 5, 2012 at 5:13 PM, Enrique notifications@github.com wrote:

> - Variable Renaming
> - Function Renaming
> - Global Undo
> - Function Extraction
> - Unfortunately did not manage to put module renaming to work
> - All the integrations work with wrangler 69def6ehttps://github.com/jimenezrick/vimerl/commit/69def6ec21f9e0b696c2150710d09ca922aa8e8b(latest)
> - Debugging traces still on
> - Keep in mind you need to put erl_call in your path!!
> 
> ---
> 
> You can merge this Pull Request by running:
> 
>   git pull https://github.com/spil-enrique/vimerl master
> 
> Or view, comment on, or merge it at:
> 
>   https://github.com/jimenezrick/vimerl/pull/30
> Commit Summary
> - NEW Added basic wrangler support up to date
> 
> File Changes
> - _A_ ftplugin/erlang_refactor.vim (295)
> 
> Patch Links
> - https://github.com/jimenezrick/vimerl/pull/30.patch
> - https://github.com/jimenezrick/vimerl/pull/30.diff
>   
>   —
>   Reply to this email directly or view it on GitHubhttps://github.com/jimenezrick/vimerl/pull/30.

## 

Ricardo

**Comment by aerosol** [comment]
@spil-enrique Thanks, I am definitely interested in that one! _cherry-pick'd_ :)

**Comment by quiquepaz** [comment]
It's not the code you removed. As you can see in the commit message, this one actually works ;)
The coolest things about Wrangler are the function renaming throughout the sorces and the function extraction. Specially the last one, as it cannot be achieved just with 'vim magic': it requires specific Erlang syntax.

Anyway, it's easy to disable the whole thing if you don't like it.

Thx for the quick answer!

Cheers!

Sent From My Phone

Ricardo Catalinas Jiménez notifications@github.com escribió:
Is this the same version I removed? As I said I'm not especially
interesting in including it, as I am not going to maintain it...

On Fri, Oct 5, 2012 at 5:13 PM, Enrique notifications@github.com wrote:

> - Variable Renaming
> - Function Renaming
> - Global Undo
> - Function Extraction
> - Unfortunately did not manage to put module renaming to work
> - All the integrations work with wrangler 69def6ehttps://github.com/jimenezrick/vimerl/commit/69def6ec21f9e0b696c2150710d09ca922aa8e8b(latest)
> - Debugging traces still on
> - Keep in mind you need to put erl_call in your path!!
> 
> ---
> 
> You can merge this Pull Request by running:
> 
> git pull https://github.com/spil-enrique/vimerl master
> 
> Or view, comment on, or merge it at:
> 
> https://github.com/jimenezrick/vimerl/pull/30
> Commit Summary
> - NEW Added basic wrangler support up to date
> 
> File Changes
> - _A_ ftplugin/erlang_refactor.vim (295)
> 
> Patch Links
> - https://github.com/jimenezrick/vimerl/pull/30.patch
> - https://github.com/jimenezrick/vimerl/pull/30.diff
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/jimenezrick/vimerl/pull/30.

## 

Ricardo

**Comment by jimenezrick** [comment]
I pulled this commit in the `wrangler-support` branch. For the moment, I'd rather prefer to keep this feature separated.

I'm willing to keep this branch rebased from master so that any user can switch to it and use this feature with the latest Vimerl. If you improve this script, send me a pull request to keep this repo updated.

I hope this suits you :-)

**Comment by quiquepaz** [comment]
Sure it suits me. Sounds like a very reasonable approach. I will let you know if I improve the script any further.

Regards!

Enrique Paz Pérez

Backend Developer

Enrique.PazPérez@spilgames.commailto:gina@spilgames.com

www.spilgames.comhttp://www.spilgames.com/ | Skype: enriquepazperez

M +31 (0) 648502292
Arendstraat 23, 1223 RE Hilversum, The Netherlands

**Pull request closed without merging**
